### ISSUE TITLE
Failing CRAN checks - due 10/16

### ISSUE THREAD

**Issue by nicklucius** [Chicago/RSocrata#183]
https://cran.r-project.org/web/checks/check_results_RSocrata.html

**Comment by geneorama** [comment]
RSocrata was pulled off CRAN, this time they didn't give much warning, just one email on 10/2.  

The only failing test I see is documented as relating to [issue 118, line 131](https://github.com/Chicago/RSocrata/blob/master/tests/testthat/test-all.R#L131). The data set is returning 146 columns instead of 150.

**Comment by nicklucius** [comment]
Changing the expected number of columns to 146 fixes the issue and all tests pass. Socrata changed the number of columns in this dataset. Since the test itself is unrelated to the number of columns, I think the fact that the test now passes means that the breakage is resolved and we should resubmit to CRAN. 

I'll start another issue to investigate the column number change as well as other inconsistencies reported by @geneorama in #118.

**Comment by nicklucius** [comment]
We are now passing CRAN checks and have submitted the package to be back on CRAN.
