### ISSUE TITLE
RSocrata removed from CRAN

### ISSUE THREAD

**Issue by ajlyons** [Chicago/RSocrata#215]
As of 8/19/2023, RSocrata is no longer on [CRAN ](https://cran.r-project.org/web/packages/RSocrata/index.html) due to 'repeated policy violation'. Hopefully that's a easy fix, because it's a critical package and installing from CRAN is a lot easier than installing from GH.

**Comment by geneorama** [comment]
This has been resubmitted to CRAN and now we wait for a response.

**Comment by geneorama** [comment]
In the last response there was an error, it appears they're still building on the old package (I missed the error because of how it was in the email). 

However, there were also some notes which should be corrected, and I'm opening an issue to address those notes. 

We will also resubmit and add comments to inform them of the issue with the tests that appear to be using a cached version of the package.

**Comment by geneorama** [comment]
We received notification that RSocrata was heading back to CRAN. Will close when confirmed.
