### ISSUE TITLE
Warning: replacing previous import by ‘curl::handle_reset’ when loading ‘RSocrata’

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/RSocrata#42]
Received via email:

> Following a recent curl update your package now gives the following warning:
>
> * checking whether package ‘RSocrata’ can be installed ... [2s/2s] WARNING Found the following significant warnings:
> Warning: replacing previous import by ‘curl::handle_reset’ when loading ‘RSocrata’
> 
> Can you pls fix?  Instead of having NAMESPACE do
> 
> import(jsonlite)
> import(httr)
> import(mime)
> import(curl)

**Comment by geneorama** [comment]
I think this is fixed in Chicago/RSocrata/iss42

I can't get the configuration right in AppVeyor, so I can't test it there, but it appears to work locally.

For some reason I had to comment out the `fieldName` example in the inline documentation.

**Comment by tomschenkjr** [comment]
@geneorama I don't see iss42 in the repo -- did you push that up to GitHub?

**Comment by geneorama** [comment]
Since this *is* issue 42, I'm not sure what I meant by this
> I think this is fixed in Chicago/RSocrata/iss42

It looks like the appropriate changes were made in 632ef0472a2eda0944f372ef3f81759c828fcde2, which I think has been merged into [dev](https://github.com/Chicago/RSocrata/tree/dev)

**Comment by geneorama** [comment]
Tom, thanks for bringing this to my attention.

Using `importFrom` is intentional, and from R documentation:
http://cran.r-project.org/doc/manuals/R-exts.html#Specifying-imports-and-exports
> Using importFrom selectively rather than import is good practice.

Originally I didn't use `importFrom` just because it was good practice, I believe it solved another problem.

Also the use of `::` is deliberate.  Although I sometimes think it's useful in general scripts, I think it's very important to use in package development. 
 - It helps track where dependencies occur, which is useful in limiting the number of dependencies.
 - It helps track where dependencies occur, which is useful in when possibly switching dependencies (e.g. switching between `curl` and `RCurl`)
 - It avoids potential namespace conflicts that could be introduced by the order in which packages are attached
 - It avoids namespace conflicts for potentially common function names (e.g. `GET`, which is currently an `httr` function, but could easily be defined elsewhere)
 - It actually simplifies development (at the cost of complicating readability) because you no longer have to worry about having complicated namespace issues

Conceptually I like having dependencies that rely on the oldest packages possible, to avoid forcing someone to update for no reason.  However, it's probably a good idea to update our versions, since this isn't something that I've been paying attention to (and I'm guessing nobody else has either).  I wonder, does CRAN use the oldest package version possible when doing the checks?

**Comment by tomschenkjr** [comment]
@geneorama - wrong thread. I think you were looking for #47. Can you copy/paste over there?
